spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    name: configure
  exchange:
    name: configure_exchange
  binding:
    name: configure_routing_key
