spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    name: configure
  exchange:
    name: configure_exchange
  routing:
    name: configure_routing_key
  json:
    queue:
      name: configure_json
    routing:
      name: configure_json_routing_key